Pokemon.create([
  {name: "Bulbasaur", pokedex_id: 1, type_1: "Poison", type_2: "Grass"},
  {name: "Ivysaur", pokedex_id: 2, type_1: "Poison", type_2: "Grass"},
  {name: "Venusaur", pokedex_id: 3, type_1: "Poison", type_2: "Grass"},
  {name: "Charmander", pokedex_id: 4, type_1: "Fire", type_2: nil},
  {name: "Charmeleon", pokedex_id: 5, type_1: "Fire", type_2: nil},
  {name: "Charizard", pokedex_id: 6, type_1: "Flying", type_2: "Fire"},
  {name: "Squirtle", pokedex_id: 7, type_1: "Water", type_2: nil},
  {name: "Wartortle", pokedex_id: 8, type_1: "Water", type_2: nil},
  {name: "Blastoise", pokedex_id: 9, type_1: "Water", type_2: nil},
  {name: "Caterpie", pokedex_id: 10, type_1: "Bug", type_2: nil},
  {name: "Metapod", pokedex_id: 11, type_1: "Bug", type_2: nil},
  {name: "Butterfree", pokedex_id: 12, type_1: "Flying", type_2: "Bug"},
  {name: "Weedle", pokedex_id: 13, type_1: "Poison", type_2: "Bug"},
  {name: "Kakuna", pokedex_id: 14, type_1: "Poison", type_2: "Bug"},
  {name: "Beedrill", pokedex_id: 15, type_1: "Poison", type_2: "Bug"},
  {name: "Pidgey", pokedex_id: 16, type_1: "Flying", type_2: "Normal"},
  {name: "Pidgeotto", pokedex_id: 17, type_1: "Flying", type_2: "Normal"},
  {name: "Pidgeot", pokedex_id: 18, type_1: "Flying", type_2: "Normal"},
  {name: "Rattata", pokedex_id: 19, type_1: "Normal", type_2: nil},
  {name: "Raticate", pokedex_id: 20, type_1: "Normal", type_2: nil},
  {name: "Spearow", pokedex_id: 21, type_1: "Flying", type_2: "Normal"},
  {name: "Fearow", pokedex_id: 22, type_1: "Flying", type_2: "Normal"},
  {name: "Ekans", pokedex_id: 23, type_1: "Poison", type_2: nil},
  {name: "Arbok", pokedex_id: 24, type_1: "Poison", type_2: nil},
  {name: "Pikachu", pokedex_id: 25, type_1: "Electric", type_2: nil},
  {name: "Raichu", pokedex_id: 26, type_1: "Electric", type_2: nil},
  {name: "Sandshrew", pokedex_id: 27, type_1: "Ground", type_2: nil},
  {name: "Sandslash", pokedex_id: 28, type_1: "Ground", type_2: nil},
  {name: "Nidoran F", pokedex_id: 29, type_1: "Poison", type_2: nil},
  {name: "Nidorina", pokedex_id: 30, type_1: "Poison", type_2: nil},
  {name: "Nidoqueen", pokedex_id: 31, type_1: "Ground", type_2: "Poison"},
  {name: "Nidoran M", pokedex_id: 32, type_1: "Poison", type_2: nil},
  {name: "Nidorino", pokedex_id: 33, type_1: "Poison", type_2: nil},
  {name: "Nidoking", pokedex_id: 34, type_1: "Ground", type_2: "Poison"},
  {name: "Clefairy", pokedex_id: 35, type_1: "Fairy", type_2: nil},
  {name: "Clefable", pokedex_id: 36, type_1: "Fairy", type_2: nil},
  {name: "Vulpix", pokedex_id: 37, type_1: "Fire", type_2: nil},
  {name: "Ninetales", pokedex_id: 38, type_1: "Fire", type_2: nil},
  {name: "Jigglypuff", pokedex_id: 39, type_1: "Fairy", type_2: "Normal"},
  {name: "Wigglytuff", pokedex_id: 40, type_1: "Fairy", type_2: "Normal"},
  {name: "Zubat", pokedex_id: 41, type_1: "Flying", type_2: "Poison"},
  {name: "Golbat", pokedex_id: 42, type_1: "Flying", type_2: "Poison"},
  {name: "Oddish", pokedex_id: 43, type_1: "Poison", type_2: "Grass"},
  {name: "Gloom", pokedex_id: 44, type_1: "Poison", type_2: "Grass"},
  {name: "Vileplume", pokedex_id: 45, type_1: "Poison", type_2: "Grass"},
  {name: "Paras", pokedex_id: 46, type_1: "Grass", type_2: "Bug"},
  {name: "Parasect", pokedex_id: 47, type_1: "Grass", type_2: "Bug"},
  {name: "Venonat", pokedex_id: 48, type_1: "Poison", type_2: "Bug"},
  {name: "Venomoth", pokedex_id: 49, type_1: "Poison", type_2: "Bug"},
  {name: "Diglett", pokedex_id: 50, type_1: "Ground", type_2: nil},
  {name: "Dugtrio", pokedex_id: 51, type_1: "Ground", type_2: nil},
  {name: "Meowth", pokedex_id: 52, type_1: "Normal", type_2: nil},
  {name: "Persian", pokedex_id: 53, type_1: "Normal", type_2: nil},
  {name: "Psyduck", pokedex_id: 54, type_1: "Water", type_2: nil},
  {name: "Golduck", pokedex_id: 55, type_1: "Water", type_2: nil},
  {name: "Mankey", pokedex_id: 56, type_1: "Fighting", type_2: nil},
  {name: "Primeape", pokedex_id: 57, type_1: "Fighting", type_2: nil},
  {name: "Growlithe", pokedex_id: 58, type_1: "Fire", type_2: nil},
  {name: "Arcanine", pokedex_id: 59, type_1: "Fire", type_2: nil},
  {name: "Poliwag", pokedex_id: 60, type_1: "Water", type_2: nil},
  {name: "Poliwhirl", pokedex_id: 61, type_1: "Water", type_2: nil},
  {name: "Poliwrath", pokedex_id: 62, type_1: "Fighting", type_2: "Water"},
  {name: "Abra", pokedex_id: 63, type_1: "Psychic", type_2: nil},
  {name: "Kadabra", pokedex_id: 64, type_1: "Psychic", type_2: nil},
  {name: "Alakazam", pokedex_id: 65, type_1: "Psychic", type_2: nil},
  {name: "Machop", pokedex_id: 66, type_1: "Fighting", type_2: nil},
  {name: "Machoke", pokedex_id: 67, type_1: "Fighting", type_2: nil},
  {name: "Machamp", pokedex_id: 68, type_1: "Fighting", type_2: nil},
  {name: "Bellsprout", pokedex_id: 69, type_1: "Poison", type_2: "Grass"},
  {name: "Weepinbell", pokedex_id: 70, type_1: "Poison", type_2: "Grass"},
  {name: "Victreebel", pokedex_id: 71, type_1: "Poison", type_2: "Grass"},
  {name: "Tentacool", pokedex_id: 72, type_1: "Poison", type_2: "Water"},
  {name: "Tentacruel", pokedex_id: 73, type_1: "Poison", type_2: "Water"},
  {name: "Geodude", pokedex_id: 74, type_1: "Ground", type_2: "Rock"},
  {name: "Graveler", pokedex_id: 75, type_1: "Ground", type_2: "Rock"},
  {name: "Golem", pokedex_id: 76, type_1: "Ground", type_2: "Rock"},
  {name: "Ponyta", pokedex_id: 77, type_1: "Fire", type_2: nil},
  {name: "Rapidash", pokedex_id: 78, type_1: "Fire", type_2: nil},
  {name: "Slowpoke", pokedex_id: 79, type_1: "Psychic", type_2: "Water"},
  {name: "Slowbro", pokedex_id: 80, type_1: "Psychic", type_2: "Water"},
  {name: "Magnemite", pokedex_id: 81, type_1: "Steel", type_2: "Electric"},
  {name: "Magneton", pokedex_id: 82, type_1: "Steel", type_2: "Electric"},
  {name: "Farfetch'd", pokedex_id: 83, type_1: "Flying", type_2: "Normal"},
  {name: "Doduo", pokedex_id: 84, type_1: "Flying", type_2: "Normal"},
  {name: "Dodrio", pokedex_id: 85, type_1: "Flying", type_2: "Normal"},
  {name: "Seel", pokedex_id: 86, type_1: "Water", type_2: nil},
  {name: "Dewgong", pokedex_id: 87, type_1: "Ice", type_2: "Water"},
  {name: "Grimer", pokedex_id: 88, type_1: "Poison", type_2: nil},
  {name: "Muk", pokedex_id: 89, type_1: "Poison", type_2: nil},
  {name: "Shellder", pokedex_id: 90, type_1: "Water", type_2: nil},
  {name: "Cloyster", pokedex_id: 91, type_1: "Ice", type_2: "Water"},
  {name: "Gastly", pokedex_id: 92, type_1: "Poison", type_2: "Ghost"},
  {name: "Haunter", pokedex_id: 93, type_1: "Poison", type_2: "Ghost"},
  {name: "Gengar", pokedex_id: 94, type_1: "Poison", type_2: "Ghost"},
  {name: "Onix", pokedex_id: 95, type_1: "Ground", type_2: "Rock"},
  {name: "Drowzee", pokedex_id: 96, type_1: "Psychic", type_2: nil},
  {name: "Hypno", pokedex_id: 97, type_1: "Psychic", type_2: nil},
  {name: "Krabby", pokedex_id: 98, type_1: "Water", type_2: nil},
  {name: "Kingler", pokedex_id: 99, type_1: "Water", type_2: nil},
  {name: "Voltorb", pokedex_id: 100, type_1: "Electric", type_2: nil},
  {name: "Electrode", pokedex_id: 101, type_1: "Electric", type_2: nil},
  {name: "Exeggcute", pokedex_id: 102, type_1: "Psychic", type_2: "Grass"},
  {name: "Exeggutor", pokedex_id: 103, type_1: "Psychic", type_2: "Grass"},
  {name: "Cubone", pokedex_id: 104, type_1: "Ground", type_2: nil},
  {name: "Marowak", pokedex_id: 105, type_1: "Ground", type_2: nil},
  {name: "Hitmonlee", pokedex_id: 106, type_1: "Fighting", type_2: nil},
  {name: "Hitmonchan", pokedex_id: 107, type_1: "Fighting", type_2: nil},
  {name: "Lickitung", pokedex_id: 108, type_1: "Normal", type_2: nil},
  {name: "Koffing", pokedex_id: 109, type_1: "Poison", type_2: nil},
  {name: "Weezing", pokedex_id: 110, type_1: "Poison", type_2: nil},
  {name: "Rhyhorn", pokedex_id: 111, type_1: "Rock", type_2: "Ground"},
  {name: "Rhydon", pokedex_id: 112, type_1: "Rock", type_2: "Ground"},
  {name: "Chansey", pokedex_id: 113, type_1: "Normal", type_2: nil},
  {name: "Tangela", pokedex_id: 114, type_1: "Grass", type_2: nil},
  {name: "Kangaskhan", pokedex_id: 115, type_1: "Normal", type_2: nil},
  {name: "Horsea", pokedex_id: 116, type_1: "Water", type_2: nil},
  {name: "Seadra", pokedex_id: 117, type_1: "Water", type_2: nil},
  {name: "Goldeen", pokedex_id: 118, type_1: "Water", type_2: nil},
  {name: "Seaking", pokedex_id: 119, type_1: "Water", type_2: nil},
  {name: "Staryu", pokedex_id: 120, type_1: "Water", type_2: nil},
  {name: "Starmie", pokedex_id: 121, type_1: "Psychic", type_2: "Water"},
  {name: "Mr.Mime", pokedex_id: 122, type_1: "Fairy", type_2: "Psychic"},
  {name: "Scyther", pokedex_id: 123, type_1: "Flying", type_2: "Bug"},
  {name: "Jynx", pokedex_id: 124, type_1: "Psychic", type_2: "Ice"},
  {name: "Electabuzz", pokedex_id: 125, type_1: "Electric", type_2: nil},
  {name: "Magmar", pokedex_id: 126, type_1: "Fire", type_2: nil},
  {name: "Pinsir", pokedex_id: 127, type_1: "Bug", type_2: nil},
  {name: "Tauros", pokedex_id: 128, type_1: "Normal", type_2: nil},
  {name: "Magikarp", pokedex_id: 129, type_1: "Water", type_2: nil},
  {name: "Gyarados", pokedex_id: 130, type_1: "Flying", type_2: "Water"},
  {name: "Lapras", pokedex_id: 131, type_1: "Ice", type_2: "Water"},
  {name: "Ditto", pokedex_id: 132, type_1: "Normal", type_2: nil},
  {name: "Eevee", pokedex_id: 133, type_1: "Normal", type_2: nil},
  {name: "Vaporeon", pokedex_id: 134, type_1: "Water", type_2: nil},
  {name: "Jolteon", pokedex_id: 135, type_1: "Electric", type_2: nil},
  {name: "Flareon", pokedex_id: 136, type_1: "Fire", type_2: nil},
  {name: "Porygon", pokedex_id: 137, type_1: "Normal", type_2: nil},
  {name: "Omanyte", pokedex_id: 138, type_1: "Water", type_2: "Rock"},
  {name: "Omastar", pokedex_id: 139, type_1: "Water", type_2: "Rock"},
  {name: "Kabuto", pokedex_id: 140, type_1: "Water", type_2: "Rock"},
  {name: "Kabutops", pokedex_id: 141, type_1: "Water", type_2: "Rock"},
  {name: "Aerodactyl", pokedex_id: 142, type_1: "Flying", type_2: "Rock"},
  {name: "Snorlax", pokedex_id: 143, type_1: "Normal", type_2: nil},
  {name: "Articuno", pokedex_id: 144, type_1: "Flying", type_2: "Ice"},
  {name: "Zapdos", pokedex_id: 145, type_1: "Flying", type_2: "Electric"},
  {name: "Moltres", pokedex_id: 146, type_1: "Flying", type_2: "Fire"},
  {name: "Dratini", pokedex_id: 147, type_1: "Dragon", type_2: nil},
  {name: "Dragonair", pokedex_id: 148, type_1: "Dragon", type_2: nil},
  {name: "Dragonite", pokedex_id: 149, type_1: "Flying", type_2: "Dragon"},
  {name: "Mewtwo", pokedex_id: 150, type_1: "Psychic", type_2: nil},
  {name: "Mew", pokedex_id: 151, type_1: "Psychic", type_2: nil}
  # {name: "Chikorita", pokedex_id: 152, type_1: "Grass", type_2: nil},
  #{name: "Bayleef", pokedex_id: 153, type_1: "Grass", type_2: nil},
  #{name: "Meganium", pokedex_id: 154, type_1: "Grass", type_2: nil},
  #{name: "Cyndaquil", pokedex_id: 155, type_1: "Fire", type_2: nil},
  #{name: "Quilava", pokedex_id: 156, type_1: "Fire", type_2: nil},
  #{name: "Typhlosion", pokedex_id: 157, type_1: "Fire", type_2: nil},
  #{name: "Totodile", pokedex_id: 158, type_1: "Water", type_2: nil},
  #{name: "Croconaw", pokedex_id: 159, type_1: "Water", type_2: nil},
  #{name: "Feraligatr", pokedex_id: 160, type_1: "Water", type_2: nil},
  #{name: "Sentret", pokedex_id: 161, type_1: "Normal", type_2: nil},
  #{name: "Furret", pokedex_id: 162, type_1: "Normal", type_2: nil},
  #{name: "Hoothoot", pokedex_id: 163, type_1: "Flying", type_2: "Normal"},
  #{name: "Noctowl", pokedex_id: 164, type_1: "Flying", type_2: "Normal"},
  #{name: "Ledyba", pokedex_id: 165, type_1: "Flying", type_2: "Bug"},
  #{name: "Ledian", pokedex_id: 166, type_1: "Flying", type_2: "Bug"},
  #{name: "Spinarak", pokedex_id: 167, type_1: "Poison", type_2: "Bug"},
  #{name: "Ariados", pokedex_id: 168, type_1: "Poison", type_2: "Bug"},
  #{name: "Crobat", pokedex_id: 169, type_1: "Flying", type_2: "Poison"},
  #{name: "Chinchou", pokedex_id: 170, type_1: "Electric", type_2: "Water"},
  #{name: "Lanturn", pokedex_id: 171, type_1: "Electric", type_2: "Water"},
  #{name: "Pichu", pokedex_id: 172, type_1: "Electric", type_2: nil},
  #{name: "Cleffa", pokedex_id: 173, type_1: "Fairy", type_2: nil},
  #{name: "Igglybuff", pokedex_id: 174, type_1: "Fairy", type_2: "Normal"},
  #{name: "Togepi", pokedex_id: 175, type_1: "Fairy", type_2: nil},
  #{name: "Togetic", pokedex_id: 176, type_1: "Flying", type_2: "Fairy"},
  #{name: "Natu", pokedex_id: 177, type_1: "Flying", type_2: "Psychic"},
  #{name: "Xatu", pokedex_id: 178, type_1: "Flying", type_2: "Psychic"},
  #{name: "Mareep", pokedex_id: 179, type_1: "Electric", type_2: nil},
  #{name: "Flaaffy", pokedex_id: 180, type_1: "Electric", type_2: nil},
  #{name: "Ampharos", pokedex_id: 181, type_1: "Electric", type_2: nil},
  #{name: "Bellossom", pokedex_id: 182, type_1: "Grass", type_2: nil},
  #{name: "Marill", pokedex_id: 183, type_1: "Fairy", type_2: "Water"},
  #{name: "Azumarill", pokedex_id: 184, type_1: "Fairy", type_2: "Water"},
  #{name: "Sudowoodo", pokedex_id: 185, type_1: "Rock", type_2: nil},
  #{name: "Politoed", pokedex_id: 186, type_1: "Water", type_2: nil},
  #{name: "Hoppip", pokedex_id: 187, type_1: "Flying", type_2: "Grass"},
  #{name: "Skiploom", pokedex_id: 188, type_1: "Flying", type_2: "Grass"},
  #{name: "Jumpluff", pokedex_id: 189, type_1: "Flying", type_2: "Grass"},
  #{name: "Aipom", pokedex_id: 190, type_1: "Normal", type_2: nil},
  #{name: "Sunkern", pokedex_id: 191, type_1: "Grass", type_2: nil},
  #{name: "Sunflora", pokedex_id: 192, type_1: "Grass", type_2: nil},
  #{name: "Yanma", pokedex_id: 193, type_1: "Flying", type_2: "Bug"},
  #{name: "Wooper", pokedex_id: 194, type_1: "Ground", type_2: "Water"},
  #{name: "Quagsire", pokedex_id: 195, type_1: "Ground", type_2: "Water"},
  #{name: "Espeon", pokedex_id: 196, type_1: "Psychic", type_2: nil},
  #{name: "Umbreon", pokedex_id: 197, type_1: "Dark", type_2: nil},
  #{name: "Murkrow", pokedex_id: 198, type_1: "Flying", type_2: "Dark"},
  #{name: "Slowking", pokedex_id: 199, type_1: "Psychic", type_2: "Water"},
  #{name: "Misdreavus", pokedex_id: 200, type_1: "Ghost", type_2: nil},
  #{name: "Unown", pokedex_id: 201, type_1: "Psychic", type_2: nil},
  #{name: "Wobbuffet", pokedex_id: 202, type_1: "Psychic", type_2: nil},
  #{name: "Girafarig", pokedex_id: 203, type_1: "Psychic", type_2: "Normal"},
  #{name: "Pineco", pokedex_id: 204, type_1: "Bug", type_2: nil},
  #{name: "Forretress", pokedex_id: 205, type_1: "Steel", type_2: "Bug"},
  #{name: "Dunsparce", pokedex_id: 206, type_1: "Normal", type_2: nil},
  #{name: "Gligar", pokedex_id: 207, type_1: "Flying", type_2: "Ground"},
  #{name: "Steelix", pokedex_id: 208, type_1: "Ground", type_2: "Steel"},
  #{name: "Snubbull", pokedex_id: 209, type_1: "Fairy", type_2: nil},
  #{name: "Granbull", pokedex_id: 210, type_1: "Fairy", type_2: nil},
  #{name: "Qwilfish", pokedex_id: 211, type_1: "Poison", type_2: "Water"},
  #{name: "Scizor", pokedex_id: 212, type_1: "Steel", type_2: "Bug"},
  #{name: "Shuckle", pokedex_id: 213, type_1: "Rock", type_2: "Bug"},
  #{name: "Heracross", pokedex_id: 214, type_1: "Fighting", type_2: "Bug"},
  #{name: "Sneasel", pokedex_id: 215, type_1: "Ice", type_2: "Dark"},
  #{name: "Teddiursa", pokedex_id: 216, type_1: "Normal", type_2: nil},
  #{name: "Ursaring", pokedex_id: 217, type_1: "Normal", type_2: nil},
  #{name: "Slugma", pokedex_id: 218, type_1: "Fire", type_2: nil},
  #{name: "Magcargo", pokedex_id: 219, type_1: "Rock", type_2: "Fire"},
  #{name: "Swinub", pokedex_id: 220, type_1: "Ground", type_2: "Ice"},
  #{name: "Piloswine", pokedex_id: 221, type_1: "Ground", type_2: "Ice"},
  #{name: "Corsola", pokedex_id: 222, type_1: "Rock", type_2: "Water"},
  #{name: "Remoraid", pokedex_id: 223, type_1: "Water", type_2: nil},
  #{name: "Octillery", pokedex_id: 224, type_1: "Water", type_2: nil},
  #{name: "Delibird", pokedex_id: 225, type_1: "Flying", type_2: "Ice"},
  #{name: "Mantine", pokedex_id: 226, type_1: "Flying", type_2: "Water"},
  #{name: "Skarmory", pokedex_id: 227, type_1: "Flying", type_2: "Steel"},
  #{name: "Houndour", pokedex_id: 228, type_1: "Fire", type_2: "Dark"},
  #{name: "Houndoom", pokedex_id: 229, type_1: "Fire", type_2: "Dark"},
  #{name: "Kingdra", pokedex_id: 230, type_1: "Dragon", type_2: "Water"},
  #{name: "Phanpy", pokedex_id: 231, type_1: "Ground", type_2: nil},
  #{name: "Donphan", pokedex_id: 232, type_1: "Ground", type_2: nil},
  #{name: "Porygon2", pokedex_id: 233, type_1: "Normal", type_2: nil},
  #{name: "Stantler", pokedex_id: 234, type_1: "Normal", type_2: nil},
  #{name: "Smeargle", pokedex_id: 235, type_1: "Normal", type_2: nil},
  #{name: "Tyrogue", pokedex_id: 236, type_1: "Fighting", type_2: nil},
  #{name: "Hitmontop", pokedex_id: 237, type_1: "Fighting", type_2: nil},
  #{name: "Smoochum", pokedex_id: 238, type_1: "Psychic", type_2: "Ice"},
  #{name: "Elekid", pokedex_id: 239, type_1: "Electric", type_2: nil},
  #{name: "Magby", pokedex_id: 240, type_1: "Fire", type_2: nil},
  #{name: "Miltank", pokedex_id: 241, type_1: "Normal", type_2: nil},
  #{name: "Blissey", pokedex_id: 242, type_1: "Normal", type_2: nil},
  #{name: "Raikou", pokedex_id: 243, type_1: "Electric", type_2: nil},
  #{name: "Entei", pokedex_id: 244, type_1: "Fire", type_2: nil},
  #{name: "Suicune", pokedex_id: 245, type_1: "Water", type_2: nil},
  #{name: "Larvitar", pokedex_id: 246, type_1: "Ground", type_2: "Rock"},
  #{name: "Pupitar", pokedex_id: 247, type_1: "Ground", type_2: "Rock"},
  #{name: "Tyranitar", pokedex_id: 248, type_1: "Dark", type_2: "Rock"},
  #{name: "Lugia", pokedex_id: 249, type_1: "Flying", type_2: "Psychic"},
  #{name: "Ho Oh", pokedex_id: 250, type_1: "Flying", type_2: "Fire"},
  #{name: "Celebi", pokedex_id: 251, type_1: "Grass", type_2: "Psychic"},
  #{name: "Treecko", pokedex_id: 252, type_1: "Grass", type_2: nil},
  #{name: "Grovyle", pokedex_id: 253, type_1: "Grass", type_2: nil},
  #{name: "Sceptile", pokedex_id: 254, type_1: "Grass", type_2: nil},
  #{name: "Torchic", pokedex_id: 255, type_1: "Fire", type_2: nil},
  #{name: "Combusken", pokedex_id: 256, type_1: "Fighting", type_2: "Fire"},
  #{name: "Blaziken", pokedex_id: 257, type_1: "Fighting", type_2: "Fire"},
  #{name: "Mudkip", pokedex_id: 258, type_1: "Water", type_2: nil},
  #{name: "Marshtomp", pokedex_id: 259, type_1: "Ground", type_2: "Water"},
  #{name: "Swampert", pokedex_id: 260, type_1: "Ground", type_2: "Water"},
  #{name: "Poochyena", pokedex_id: 261, type_1: "Dark", type_2: nil},
  #{name: "Mightyena", pokedex_id: 262, type_1: "Dark", type_2: nil},
  #{name: "Zigzagoon", pokedex_id: 263, type_1: "Normal", type_2: nil},
  #{name: "Linoone", pokedex_id: 264, type_1: "Normal", type_2: nil},
  #{name: "Wurmple", pokedex_id: 265, type_1: "Bug", type_2: nil},
  #{name: "Silcoon", pokedex_id: 266, type_1: "Bug", type_2: nil},
  #{name: "Beautifly", pokedex_id: 267, type_1: "Flying", type_2: "Bug"},
  #{name: "Cascoon", pokedex_id: 268, type_1: "Bug", type_2: nil},
  #{name: "Dustox", pokedex_id: 269, type_1: "Poison", type_2: "Bug"},
  #{name: "Lotad", pokedex_id: 270, type_1: "Grass", type_2: "Water"},
  #{name: "Lombre", pokedex_id: 271, type_1: "Grass", type_2: "Water"},
  #{name: "Ludicolo", pokedex_id: 272, type_1: "Grass", type_2: "Water"},
  #{name: "Seedot", pokedex_id: 273, type_1: "Grass", type_2: nil},
  #{name: "Nuzleaf", pokedex_id: 274, type_1: "Dark", type_2: "Grass"},
  #{name: "Shiftry", pokedex_id: 275, type_1: "Dark", type_2: "Grass"},
  #{name: "Taillow", pokedex_id: 276, type_1: "Flying", type_2: "Normal"},
  #{name: "Swellow", pokedex_id: 277, type_1: "Flying", type_2: "Normal"},
  #{name: "Wingull", pokedex_id: 278, type_1: "Flying", type_2: "Water"},
  #{name: "Pelipper", pokedex_id: 279, type_1: "Flying", type_2: "Water"},
  #{name: "Ralts", pokedex_id: 280, type_1: "Fairy", type_2: "Psychic"},
  #{name: "Kirlia", pokedex_id: 281, type_1: "Fairy", type_2: "Psychic"},
  #{name: "Gardevoir", pokedex_id: 282, type_1: "Fairy", type_2: "Psychic"},
  #{name: "Surskit", pokedex_id: 283, type_1: "Water", type_2: "Bug"},
  #{name: "Masquerain", pokedex_id: 284, type_1: "Flying", type_2: "Bug"},
  #{name: "Shroomish", pokedex_id: 285, type_1: "Grass", type_2: nil},
  #{name: "Breloom", pokedex_id: 286, type_1: "Fighting", type_2: "Grass"},
  #{name: "Slakoth", pokedex_id: 287, type_1: "Normal", type_2: nil},
  #{name: "Vigoroth", pokedex_id: 288, type_1: "Normal", type_2: nil},
  #{name: "Slaking", pokedex_id: 289, type_1: "Normal", type_2: nil},
  #{name: "Nincada", pokedex_id: 290, type_1: "Ground", type_2: "Bug"},
  #{name: "Ninjask", pokedex_id: 291, type_1: "Flying", type_2: "Bug"},
  #{name: "Shedinja", pokedex_id: 292, type_1: "Ghost", type_2: "Bug"},
  #{name: "Whismur", pokedex_id: 293, type_1: "Normal", type_2: nil},
  #{name: "Loudred", pokedex_id: 294, type_1: "Normal", type_2: nil},
  #{name: "Exploud", pokedex_id: 295, type_1: "Normal", type_2: nil},
  #{name: "Makuhita", pokedex_id: 296, type_1: "Fighting", type_2: nil},
  #{name: "Hariyama", pokedex_id: 297, type_1: "Fighting", type_2: nil},
  #{name: "Azurill", pokedex_id: 298, type_1: "Fairy", type_2: "Normal"},
  #{name: "Nosepass", pokedex_id: 299, type_1: "Rock", type_2: nil},
  #{name: "Skitty", pokedex_id: 300, type_1: "Normal", type_2: nil},
  #{name: "Delcatty", pokedex_id: 301, type_1: "Normal", type_2: nil},
  #{name: "Sableye", pokedex_id: 302, type_1: "Ghost", type_2: "Dark"},
  #{name: "Mawile", pokedex_id: 303, type_1: "Fairy", type_2: "Steel"},
  #{name: "Aron", pokedex_id: 304, type_1: "Rock", type_2: "Steel"},
  #{name: "Lairon", pokedex_id: 305, type_1: "Rock", type_2: "Steel"},
  #{name: "Aggron", pokedex_id: 306, type_1: "Rock", type_2: "Steel"},
  #{name: "Meditite", pokedex_id: 307, type_1: "Psychic", type_2: "Fighting"},
  #{name: "Medicham", pokedex_id: 308, type_1: "Psychic", type_2: "Fighting"},
  #{name: "Electrike", pokedex_id: 309, type_1: "Electric", type_2: nil},
  #{name: "Manectric", pokedex_id: 310, type_1: "Electric", type_2: nil},
  #{name: "Plusle", pokedex_id: 311, type_1: "Electric", type_2: nil},
  #{name: "Minun", pokedex_id: 312, type_1: "Electric", type_2: nil},
  #{name: "Volbeat", pokedex_id: 313, type_1: "Bug", type_2: nil},
  #{name: "Illumise", pokedex_id: 314, type_1: "Bug", type_2: nil},
  #{name: "Roselia", pokedex_id: 315, type_1: "Poison", type_2: "Grass"},
  #{name: "Gulpin", pokedex_id: 316, type_1: "Poison", type_2: nil},
  #{name: "Swalot", pokedex_id: 317, type_1: "Poison", type_2: nil},
  #{name: "Carvanha", pokedex_id: 318, type_1: "Dark", type_2: "Water"},
  #{name: "Sharpedo", pokedex_id: 319, type_1: "Dark", type_2: "Water"},
  #{name: "Wailmer", pokedex_id: 320, type_1: "Water", type_2: nil},
  #{name: "Wailord", pokedex_id: 321, type_1: "Water", type_2: nil},
  #{name: "Numel", pokedex_id: 322, type_1: "Ground", type_2: "Fire"},
  #{name: "Camerupt", pokedex_id: 323, type_1: "Ground", type_2: "Fire"},
  #{name: "Torkoal", pokedex_id: 324, type_1: "Fire", type_2: nil},
  #{name: "Spoink", pokedex_id: 325, type_1: "Psychic", type_2: nil},
  #{name: "Grumpig", pokedex_id: 326, type_1: "Psychic", type_2: nil},
  #{name: "Spinda", pokedex_id: 327, type_1: "Normal", type_2: nil},
  #{name: "Trapinch", pokedex_id: 328, type_1: "Ground", type_2: nil},
  #{name: "Vibrava", pokedex_id: 329, type_1: "Dragon", type_2: "Ground"},
  #{name: "Flygon", pokedex_id: 330, type_1: "Dragon", type_2: "Ground"},
  #{name: "Cacnea", pokedex_id: 331, type_1: "Grass", type_2: nil},
  #{name: "Cacturne", pokedex_id: 332, type_1: "Dark", type_2: "Grass"},
  #{name: "Swablu", pokedex_id: 333, type_1: "Flying", type_2: "Normal"},
  #{name: "Altaria", pokedex_id: 334, type_1: "Flying", type_2: "Dragon"},
  #{name: "Zangoose", pokedex_id: 335, type_1: "Normal", type_2: nil},
  #{name: "Seviper", pokedex_id: 336, type_1: "Poison", type_2: nil},
  #{name: "Lunatone", pokedex_id: 337, type_1: "Psychic", type_2: "Rock"},
  #{name: "Solrock", pokedex_id: 338, type_1: "Psychic", type_2: "Rock"},
  #{name: "Barboach", pokedex_id: 339, type_1: "Ground", type_2: "Water"},
  #{name: "Whiscash", pokedex_id: 340, type_1: "Ground", type_2: "Water"},
  #{name: "Corphish", pokedex_id: 341, type_1: "Water", type_2: nil},
  #{name: "Crawdaunt", pokedex_id: 342, type_1: "Dark", type_2: "Water"},
  #{name: "Baltoy", pokedex_id: 343, type_1: "Psychic", type_2: "Ground"},
  #{name: "Claydol", pokedex_id: 344, type_1: "Psychic", type_2: "Ground"},
  #{name: "Lileep", pokedex_id: 345, type_1: "Grass", type_2: "Rock"},
  #{name: "Cradily", pokedex_id: 346, type_1: "Grass", type_2: "Rock"},
  #{name: "Anorith", pokedex_id: 347, type_1: "Bug", type_2: "Rock"},
  #{name: "Armaldo", pokedex_id: 348, type_1: "Bug", type_2: "Rock"},
  #{name: "Feebas", pokedex_id: 349, type_1: "Water", type_2: nil},
  #{name: "Milotic", pokedex_id: 350, type_1: "Water", type_2: nil},
  #{name: "Castform", pokedex_id: 351, type_1: "Normal", type_2: nil},
  #{name: "Kecleon", pokedex_id: 352, type_1: "Normal", type_2: nil},
  #{name: "Shuppet", pokedex_id: 353, type_1: "Ghost", type_2: nil},
  #{name: "Banette", pokedex_id: 354, type_1: "Ghost", type_2: nil},
  #{name: "Duskull", pokedex_id: 355, type_1: "Ghost", type_2: nil},
  #{name: "Dusclops", pokedex_id: 356, type_1: "Ghost", type_2: nil},
  #{name: "Tropius", pokedex_id: 357, type_1: "Flying", type_2: "Grass"},
  #{name: "Chimecho", pokedex_id: 358, type_1: "Psychic", type_2: nil},
  #{name: "Absol", pokedex_id: 359, type_1: "Dark", type_2: nil},
  #{name: "Wynaut", pokedex_id: 360, type_1: "Psychic", type_2: nil},
  #{name: "Snorunt", pokedex_id: 361, type_1: "Ice", type_2: nil},
  #{name: "Glalie", pokedex_id: 362, type_1: "Ice", type_2: nil},
  #{name: "Spheal", pokedex_id: 363, type_1: "Water", type_2: "Ice"},
  #{name: "Sealeo", pokedex_id: 364, type_1: "Water", type_2: "Ice"},
  #{name: "Walrein", pokedex_id: 365, type_1: "Water", type_2: "Ice"},
  #{name: "Clamperl", pokedex_id: 366, type_1: "Water", type_2: nil},
  #{name: "Huntail", pokedex_id: 367, type_1: "Water", type_2: nil},
  #{name: "Gorebyss", pokedex_id: 368, type_1: "Water", type_2: nil},
  #{name: "Relicanth", pokedex_id: 369, type_1: "Rock", type_2: "Water"},
  #{name: "Luvdisc", pokedex_id: 370, type_1: "Water", type_2: nil},
  #{name: "Bagon", pokedex_id: 371, type_1: "Dragon", type_2: nil},
  #{name: "Shelgon", pokedex_id: 372, type_1: "Dragon", type_2: nil},
  #{name: "Salamence", pokedex_id: 373, type_1: "Flying", type_2: "Dragon"},
  #{name: "Beldum", pokedex_id: 374, type_1: "Psychic", type_2: "Steel"},
  #{name: "Metang", pokedex_id: 375, type_1: "Psychic", type_2: "Steel"},
  #{name: "Metagross", pokedex_id: 376, type_1: "Psychic", type_2: "Steel"},
  #{name: "Regirock", pokedex_id: 377, type_1: "Rock", type_2: nil},
  #{name: "RegIce", pokedex_id: 378, type_1: "Ice", type_2: nil},
  #{name: "Registeel", pokedex_id: 379, type_1: "Steel", type_2: nil},
  #{name: "Latias", pokedex_id: 380, type_1: "Psychic", type_2: "Dragon"},
  #{name: "Latios", pokedex_id: 381, type_1: "Psychic", type_2: "Dragon"},
  #{name: "Kyogre", pokedex_id: 382, type_1: "Water", type_2: nil},
  #{name: "Groudon", pokedex_id: 383, type_1: "Ground", type_2: nil},
  #{name: "Rayquaza", pokedex_id: 384, type_1: "Flying", type_2: "Dragon"},
  #{name: "Jirachi", pokedex_id: 385, type_1: "Psychic", type_2: "Steel"},
  #{name: "Deoxys Normal", pokedex_id: 386, type_1: "Psychic", type_2: nil},
  #{name: "Turtwig", pokedex_id: 387, type_1: "Grass", type_2: nil},
  #{name: "Grotle", pokedex_id: 388, type_1: "Grass", type_2: nil},
  #{name: "Torterra", pokedex_id: 389, type_1: "Ground", type_2: "Grass"},
  #{name: "Chimchar", pokedex_id: 390, type_1: "Fire", type_2: nil},
  #{name: "Monferno", pokedex_id: 391, type_1: "Fighting", type_2: "Fire"},
  #{name: "Infernape", pokedex_id: 392, type_1: "Fighting", type_2: "Fire"},
  #{name: "Piplup", pokedex_id: 393, type_1: "Water", type_2: nil},
  #{name: "Prinplup", pokedex_id: 394, type_1: "Water", type_2: nil},
  #{name: "Empoleon", pokedex_id: 395, type_1: "Steel", type_2: "Water"},
  #{name: "Starly", pokedex_id: 396, type_1: "Flying", type_2: "Normal"},
  #{name: "Staravia", pokedex_id: 397, type_1: "Flying", type_2: "Normal"},
  #{name: "Staraptor", pokedex_id: 398, type_1: "Flying", type_2: "Normal"},
  #{name: "Bidoof", pokedex_id: 399, type_1: "Normal", type_2: nil},
  #{name: "Bibarel", pokedex_id: 400, type_1: "Water", type_2: "Normal"},
  #{name: "Kricketot", pokedex_id: 401, type_1: "Bug", type_2: nil},
  #{name: "Kricketune", pokedex_id: 402, type_1: "Bug", type_2: nil},
  #{name: "Shinx", pokedex_id: 403, type_1: "Electric", type_2: nil},
  #{name: "Luxio", pokedex_id: 404, type_1: "Electric", type_2: nil},
  #{name: "Luxray", pokedex_id: 405, type_1: "Electric", type_2: nil},
  #{name: "Budew", pokedex_id: 406, type_1: "Poison", type_2: "Grass"},
  #{name: "Roserade", pokedex_id: 407, type_1: "Poison", type_2: "Grass"},
  #{name: "Cranidos", pokedex_id: 408, type_1: "Rock", type_2: nil},
  #{name: "Rampardos", pokedex_id: 409, type_1: "Rock", type_2: nil},
  #{name: "Shieldon", pokedex_id: 410, type_1: "Steel", type_2: "Rock"},
  #{name: "Bastiodon", pokedex_id: 411, type_1: "Steel", type_2: "Rock"},
  #{name: "Burmy", pokedex_id: 412, type_1: "Bug", type_2: nil},
  #{name: "Wormadam Plant", pokedex_id: 413, type_1: "Grass", type_2: "Bug"},
  #{name: "Mothim", pokedex_id: 414, type_1: "Flying", type_2: "Bug"},
  #{name: "Combee", pokedex_id: 415, type_1: "Flying", type_2: "Bug"},
  #{name: "Vespiquen", pokedex_id: 416, type_1: "Flying", type_2: "Bug"},
  #{name: "Pachirisu", pokedex_id: 417, type_1: "Electric", type_2: nil},
  #{name: "Buizel", pokedex_id: 418, type_1: "Water", type_2: nil},
  #{name: "Floatzel", pokedex_id: 419, type_1: "Water", type_2: nil},
  #{name: "Cherubi", pokedex_id: 420, type_1: "Grass", type_2: nil},
  #{name: "Cherrim", pokedex_id: 421, type_1: "Grass", type_2: nil},
  #{name: "Shellos", pokedex_id: 422, type_1: "Water", type_2: nil},
  #{name: "Gastrodon", pokedex_id: 423, type_1: "Ground", type_2: "Water"},
  #{name: "Ambipom", pokedex_id: 424, type_1: "Normal", type_2: nil},
  #{name: "Drifloon", pokedex_id: 425, type_1: "Flying", type_2: "Ghost"},
  #{name: "Drifblim", pokedex_id: 426, type_1: "Flying", type_2: "Ghost"},
  #{name: "Buneary", pokedex_id: 427, type_1: "Normal", type_2: nil},
  #{name: "Lopunny", pokedex_id: 428, type_1: "Normal", type_2: nil},
  #{name: "Mismagius", pokedex_id: 429, type_1: "Ghost", type_2: nil},
  #{name: "Honchkrow", pokedex_id: 430, type_1: "Flying", type_2: "Dark"},
  #{name: "Glameow", pokedex_id: 431, type_1: "Normal", type_2: nil},
  #{name: "Purugly", pokedex_id: 432, type_1: "Normal", type_2: nil},
  #{name: "Chingling", pokedex_id: 433, type_1: "Psychic", type_2: nil},
  #{name: "Stunky", pokedex_id: 434, type_1: "Dark", type_2: "Poison"},
  #{name: "Skuntank", pokedex_id: 435, type_1: "Dark", type_2: "Poison"},
  #{name: "Bronzor", pokedex_id: 436, type_1: "Psychic", type_2: "Steel"},
  #{name: "Bronzong", pokedex_id: 437, type_1: "Psychic", type_2: "Steel"},
  #{name: "Bonsly", pokedex_id: 438, type_1: "Rock", type_2: nil},
  #{name: "Mime Jr", pokedex_id: 439, type_1: "Fairy", type_2: "Psychic"},
  #{name: "Happiny", pokedex_id: 440, type_1: "Normal", type_2: nil},
  #{name: "Chatot", pokedex_id: 441, type_1: "Flying", type_2: "Normal"},
  #{name: "Spiritomb", pokedex_id: 442, type_1: "Dark", type_2: "Ghost"},
  #{name: "Gible", pokedex_id: 443, type_1: "Ground", type_2: "Dragon"},
  #{name: "Gabite", pokedex_id: 444, type_1: "Ground", type_2: "Dragon"},
  #{name: "Garchomp", pokedex_id: 445, type_1: "Ground", type_2: "Dragon"},
  #{name: "Munchlax", pokedex_id: 446, type_1: "Normal", type_2: nil},
  #{name: "Riolu", pokedex_id: 447, type_1: "Fighting", type_2: nil},
  #{name: "Lucario", pokedex_id: 448, type_1: "Steel", type_2: "Fighting"},
  #{name: "Hippopotas", pokedex_id: 449, type_1: "Ground", type_2: nil},
  #{name: "Hippowdon", pokedex_id: 450, type_1: "Ground", type_2: nil},
  #{name: "Skorupi", pokedex_id: 451, type_1: "Bug", type_2: "Poison"},
  #{name: "Drapion", pokedex_id: 452, type_1: "Dark", type_2: "Poison"},
  #{name: "Croagunk", pokedex_id: 453, type_1: "Fighting", type_2: "Poison"},
  #{name: "Toxicroak", pokedex_id: 454, type_1: "Fighting", type_2: "Poison"},
  #{name: "Carnivine", pokedex_id: 455, type_1: "Grass", type_2: nil},
  #{name: "Finneon", pokedex_id: 456, type_1: "Water", type_2: nil},
  #{name: "Lumineon", pokedex_id: 457, type_1: "Water", type_2: nil},
  #{name: "Mantyke", pokedex_id: 458, type_1: "Flying", type_2: "Water"},
  #{name: "Snover", pokedex_id: 459, type_1: "Ice", type_2: "Grass"},
  #{name: "Abomasnow", pokedex_id: 460, type_1: "Ice", type_2: "Grass"},
  #{name: "Weavile", pokedex_id: 461, type_1: "Ice", type_2: "Dark"},
  #{name: "Magnezone", pokedex_id: 462, type_1: "Steel", type_2: "Electric"},
  #{name: "Lickilicky", pokedex_id: 463, type_1: "Normal", type_2: nil},
  #{name: "Rhyperior", pokedex_id: 464, type_1: "Rock", type_2: "Ground"},
  #{name: "Tangrowth", pokedex_id: 465, type_1: "Grass", type_2: nil},
  #{name: "Electivire", pokedex_id: 466, type_1: "Electric", type_2: nil},
  #{name: "Magmortar", pokedex_id: 467, type_1: "Fire", type_2: nil},
  #{name: "Togekiss", pokedex_id: 468, type_1: "Flying", type_2: "Fairy"},
  #{name: "Yanmega", pokedex_id: 469, type_1: "Flying", type_2: "Bug"},
  #{name: "Leafeon", pokedex_id: 470, type_1: "Grass", type_2: nil},
  #{name: "Glaceon", pokedex_id: 471, type_1: "Ice", type_2: nil},
  #{name: "Gliscor", pokedex_id: 472, type_1: "Flying", type_2: "Ground"},
  #{name: "Mamoswine", pokedex_id: 473, type_1: "Ground", type_2: "Ice"},
  #{name: "Porygon Z", pokedex_id: 474, type_1: "Normal", type_2: nil},
  #{name: "Gallade", pokedex_id: 475, type_1: "Fighting", type_2: "Psychic"},
  #{name: "Probopass", pokedex_id: 476, type_1: "Steel", type_2: "Rock"},
  #{name: "Dusknoir", pokedex_id: 477, type_1: "Ghost", type_2: nil},
  #{name: "Froslass", pokedex_id: 478, type_1: "Ghost", type_2: "Ice"},
  #{name: "Rotom", pokedex_id: 479, type_1: "Ghost", type_2: "Electric"},
  #{name: "Uxie", pokedex_id: 480, type_1: "Psychic", type_2: nil},
  #{name: "Mesprit", pokedex_id: 481, type_1: "Psychic", type_2: nil},
  #{name: "Azelf", pokedex_id: 482, type_1: "Psychic", type_2: nil},
  #{name: "Dialga", pokedex_id: 483, type_1: "Dragon", type_2: "Steel"},
  #{name: "Palkia", pokedex_id: 484, type_1: "Dragon", type_2: "Water"},
  #{name: "Heatran", pokedex_id: 485, type_1: "Steel", type_2: "Fire"},
  #{name: "Regigigas", pokedex_id: 486, type_1: "Normal", type_2: nil},
  #{name: "Giratina Altered", pokedex_id: 487, type_1: "Dragon", type_2: "Ghost"},
  #{name: "Cresselia", pokedex_id: 488, type_1: "Psychic", type_2: nil},
  #{name: "Phione", pokedex_id: 489, type_1: "Water", type_2: nil},
  #{name: "Manaphy", pokedex_id: 490, type_1: "Water", type_2: nil},
  #{name: "Darkrai", pokedex_id: 491, type_1: "Dark", type_2: nil},
  #{name: "Shaymin Land", pokedex_id: 492, type_1: "Grass", type_2: nil},
  #{name: "Arceus", pokedex_id: 493, type_1: "Normal", type_2: nil},
  #{name: "Victini", pokedex_id: 494, type_1: "Fire", type_2: "Psychic"},
  #{name: "Snivy", pokedex_id: 495, type_1: "Grass", type_2: nil},
  #{name: "Servine", pokedex_id: 496, type_1: "Grass", type_2: nil},
  #{name: "Serperior", pokedex_id: 497, type_1: "Grass", type_2: nil},
  #{name: "Tepig", pokedex_id: 498, type_1: "Fire", type_2: nil},
  #{name: "Pignite", pokedex_id: 499, type_1: "Fighting", type_2: "Fire"},
  #{name: "Emboar", pokedex_id: 500, type_1: "Fighting", type_2: "Fire"},
  #{name: "Oshawott", pokedex_id: 501, type_1: "Water", type_2: nil},
  #{name: "Dewott", pokedex_id: 502, type_1: "Water", type_2: nil},
  #{name: "Samurott", pokedex_id: 503, type_1: "Water", type_2: nil},
  #{name: "Patrat", pokedex_id: 504, type_1: "Normal", type_2: nil},
  #{name: "Watchog", pokedex_id: 505, type_1: "Normal", type_2: nil},
  #{name: "Lillipup", pokedex_id: 506, type_1: "Normal", type_2: nil},
  #{name: "Herdier", pokedex_id: 507, type_1: "Normal", type_2: nil},
  #{name: "Stoutland", pokedex_id: 508, type_1: "Normal", type_2: nil},
  #{name: "Purrloin", pokedex_id: 509, type_1: "Dark", type_2: nil},
  #{name: "Liepard", pokedex_id: 510, type_1: "Dark", type_2: nil},
  #{name: "Pansage", pokedex_id: 511, type_1: "Grass", type_2: nil},
  #{name: "Simisage", pokedex_id: 512, type_1: "Grass", type_2: nil},
  #{name: "Pansear", pokedex_id: 513, type_1: "Fire", type_2: nil},
  #{name: "Simisear", pokedex_id: 514, type_1: "Fire", type_2: nil},
  #{name: "Panpour", pokedex_id: 515, type_1: "Water", type_2: nil},
  #{name: "Simipour", pokedex_id: 516, type_1: "Water", type_2: nil},
  #{name: "Munna", pokedex_id: 517, type_1: "Psychic", type_2: nil},
  #{name: "Musharna", pokedex_id: 518, type_1: "Psychic", type_2: nil},
  #{name: "Pidove", pokedex_id: 519, type_1: "Flying", type_2: "Normal"},
  #{name: "Tranquill", pokedex_id: 520, type_1: "Flying", type_2: "Normal"},
  #{name: "Unfezant", pokedex_id: 521, type_1: "Flying", type_2: "Normal"},
  #{name: "Blitzle", pokedex_id: 522, type_1: "Electric", type_2: nil},
  #{name: "Zebstrika", pokedex_id: 523, type_1: "Electric", type_2: nil},
  #{name: "Roggenrola", pokedex_id: 524, type_1: "Rock", type_2: nil},
  #{name: "Boldore", pokedex_id: 525, type_1: "Rock", type_2: nil},
  #{name: "Gigalith", pokedex_id: 526, type_1: "Rock", type_2: nil},
  #{name: "Woobat", pokedex_id: 527, type_1: "Flying", type_2: "Psychic"},
  #{name: "Swoobat", pokedex_id: 528, type_1: "Flying", type_2: "Psychic"},
  #{name: "Drilbur", pokedex_id: 529, type_1: "Ground", type_2: nil},
  #{name: "Excadrill", pokedex_id: 530, type_1: "Steel", type_2: "Ground"},
  #{name: "Audino", pokedex_id: 531, type_1: "Normal", type_2: nil},
  #{name: "Timburr", pokedex_id: 532, type_1: "Fighting", type_2: nil},
  #{name: "Gurdurr", pokedex_id: 533, type_1: "Fighting", type_2: nil},
  #{name: "Conkeldurr", pokedex_id: 534, type_1: "Fighting", type_2: nil},
  #{name: "Tympole", pokedex_id: 535, type_1: "Water", type_2: nil},
  #{name: "Palpitoad", pokedex_id: 536, type_1: "Ground", type_2: "Water"},
  #{name: "Seismitoad", pokedex_id: 537, type_1: "Ground", type_2: "Water"},
  #{name: "Throh", pokedex_id: 538, type_1: "Fighting", type_2: nil},
  #{name: "Sawk", pokedex_id: 539, type_1: "Fighting", type_2: nil},
  #{name: "Sewaddle", pokedex_id: 540, type_1: "Grass", type_2: "Bug"},
  #{name: "Swadloon", pokedex_id: 541, type_1: "Grass", type_2: "Bug"},
  #{name: "Leavanny", pokedex_id: 542, type_1: "Grass", type_2: "Bug"},
  #{name: "Venipede", pokedex_id: 543, type_1: "Poison", type_2: "Bug"},
  #{name: "Whirlipede", pokedex_id: 544, type_1: "Poison", type_2: "Bug"},
  #{name: "Scolipede", pokedex_id: 545, type_1: "Poison", type_2: "Bug"},
  #{name: "Cottonee", pokedex_id: 546, type_1: "Fairy", type_2: "Grass"},
  #{name: "Whimsicott", pokedex_id: 547, type_1: "Fairy", type_2: "Grass"},
  #{name: "Petilil", pokedex_id: 548, type_1: "Grass", type_2: nil},
  #{name: "Lilligant", pokedex_id: 549, type_1: "Grass", type_2: nil},
  #{name: "Basculin Red Striped", pokedex_id: 550, type_1: "Water", type_2: nil},
  #{name: "Sandile", pokedex_id: 551, type_1: "Dark", type_2: "Ground"},
  #{name: "Krokorok", pokedex_id: 552, type_1: "Dark", type_2: "Ground"},
  #{name: "Krookodile", pokedex_id: 553, type_1: "Dark", type_2: "Ground"},
  #{name: "Darumaka", pokedex_id: 554, type_1: "Fire", type_2: nil},
  #{name: "Darmanitan Standard", pokedex_id: 555, type_1: "Fire", type_2: nil},
  #{name: "Maractus", pokedex_id: 556, type_1: "Grass", type_2: nil},
  #{name: "Dwebble", pokedex_id: 557, type_1: "Rock", type_2: "Bug"},
  #{name: "Crustle", pokedex_id: 558, type_1: "Rock", type_2: "Bug"},
  #{name: "Scraggy", pokedex_id: 559, type_1: "Fighting", type_2: "Dark"},
  #{name: "Scrafty", pokedex_id: 560, type_1: "Fighting", type_2: "Dark"},
  #{name: "Sigilyph", pokedex_id: 561, type_1: "Flying", type_2: "Psychic"},
  #{name: "Yamask", pokedex_id: 562, type_1: "Ghost", type_2: nil},
  #{name: "Cofagrigus", pokedex_id: 563, type_1: "Ghost", type_2: nil},
  #{name: "Tirtouga", pokedex_id: 564, type_1: "Rock", type_2: "Water"},
  #{name: "Carracosta", pokedex_id: 565, type_1: "Rock", type_2: "Water"},
  #{name: "Archen", pokedex_id: 566, type_1: "Flying", type_2: "Rock"},
  #{name: "Archeops", pokedex_id: 567, type_1: "Flying", type_2: "Rock"},
  #{name: "Trubbish", pokedex_id: 568, type_1: "Poison", type_2: nil},
  #{name: "Garbodor", pokedex_id: 569, type_1: "Poison", type_2: nil},
  #{name: "Zorua", pokedex_id: 570, type_1: "Dark", type_2: nil},
  #{name: "Zoroark", pokedex_id: 571, type_1: "Dark", type_2: nil},
  #{name: "Minccino", pokedex_id: 572, type_1: "Normal", type_2: nil},
  #{name: "Cinccino", pokedex_id: 573, type_1: "Normal", type_2: nil},
  #{name: "Gothita", pokedex_id: 574, type_1: "Psychic", type_2: nil},
  #{name: "Gothorita", pokedex_id: 575, type_1: "Psychic", type_2: nil},
  #{name: "Gothitelle", pokedex_id: 576, type_1: "Psychic", type_2: nil},
  #{name: "Solosis", pokedex_id: 577, type_1: "Psychic", type_2: nil},
  #{name: "Duosion", pokedex_id: 578, type_1: "Psychic", type_2: nil},
  #{name: "Reuniclus", pokedex_id: 579, type_1: "Psychic", type_2: nil},
  #{name: "Ducklett", pokedex_id: 580, type_1: "Flying", type_2: "Water"},
  #{name: "Swanna", pokedex_id: 581, type_1: "Flying", type_2: "Water"},
  #{name: "Vanillite", pokedex_id: 582, type_1: "Ice", type_2: nil},
  #{name: "Vanillish", pokedex_id: 583, type_1: "Ice", type_2: nil},
  #{name: "Vanilluxe", pokedex_id: 584, type_1: "Ice", type_2: nil},
  #{name: "Deerling", pokedex_id: 585, type_1: "Grass", type_2: "Normal"},
  #{name: "Sawsbuck", pokedex_id: 586, type_1: "Grass", type_2: "Normal"},
  #{name: "Emolga", pokedex_id: 587, type_1: "Flying", type_2: "Electric"},
  #{name: "Karrablast", pokedex_id: 588, type_1: "Bug", type_2: nil},
  #{name: "Escavalier", pokedex_id: 589, type_1: "Steel", type_2: "Bug"},
  #{name: "Foongus", pokedex_id: 590, type_1: "Poison", type_2: "Grass"},
  #{name: "Amoonguss", pokedex_id: 591, type_1: "Poison", type_2: "Grass"},
  #{name: "Frillish", pokedex_id: 592, type_1: "Ghost", type_2: "Water"},
  #{name: "JellIcent", pokedex_id: 593, type_1: "Ghost", type_2: "Water"},
  #{name: "Alomomola", pokedex_id: 594, type_1: "Water", type_2: nil},
  #{name: "Joltik", pokedex_id: 595, type_1: "Electric", type_2: "Bug"},
  #{name: "Galvantula", pokedex_id: 596, type_1: "Electric", type_2: "Bug"},
  #{name: "Ferroseed", pokedex_id: 597, type_1: "Steel", type_2: "Grass"},
  #{name: "Ferrothorn", pokedex_id: 598, type_1: "Steel", type_2: "Grass"},
  #{name: "Klink", pokedex_id: 599, type_1: "Steel", type_2: nil},
  #{name: "Klang", pokedex_id: 600, type_1: "Steel", type_2: nil},
  #{name: "Klinklang", pokedex_id: 601, type_1: "Steel", type_2: nil},
  #{name: "Tynamo", pokedex_id: 602, type_1: "Electric", type_2: nil},
  #{name: "Eelektrik", pokedex_id: 603, type_1: "Electric", type_2: nil},
  #{name: "Eelektross", pokedex_id: 604, type_1: "Electric", type_2: nil},
  #{name: "Elgyem", pokedex_id: 605, type_1: "Psychic", type_2: nil},
  #{name: "Beheeyem", pokedex_id: 606, type_1: "Psychic", type_2: nil},
  #{name: "Litwick", pokedex_id: 607, type_1: "Fire", type_2: "Ghost"},
  #{name: "Lampent", pokedex_id: 608, type_1: "Fire", type_2: "Ghost"},
  #{name: "Chandelure", pokedex_id: 609, type_1: "Fire", type_2: "Ghost"},
  #{name: "Axew", pokedex_id: 610, type_1: "Dragon", type_2: nil},
  #{name: "Fraxure", pokedex_id: 611, type_1: "Dragon", type_2: nil},
  #{name: "Haxorus", pokedex_id: 612, type_1: "Dragon", type_2: nil},
  #{name: "Cubchoo", pokedex_id: 613, type_1: "Ice", type_2: nil},
  #{name: "Beartic", pokedex_id: 614, type_1: "Ice", type_2: nil},
  #{name: "Cryogonal", pokedex_id: 615, type_1: "Ice", type_2: nil},
  #{name: "Shelmet", pokedex_id: 616, type_1: "Bug", type_2: nil},
  #{name: "Accelgor", pokedex_id: 617, type_1: "Bug", type_2: nil},
  #{name: "Stunfisk", pokedex_id: 618, type_1: "Electric", type_2: "Ground"},
  #{name: "Mienfoo", pokedex_id: 619, type_1: "Fighting", type_2: nil},
  #{name: "Mienshao", pokedex_id: 620, type_1: "Fighting", type_2: nil},
  #{name: "Druddigon", pokedex_id: 621, type_1: "Dragon", type_2: nil},
  #{name: "Golett", pokedex_id: 622, type_1: "Ghost", type_2: "Ground"},
  #{name: "Golurk", pokedex_id: 623, type_1: "Ghost", type_2: "Ground"},
  #{name: "Pawniard", pokedex_id: 624, type_1: "Steel", type_2: "Dark"},
  #{name: "Bisharp", pokedex_id: 625, type_1: "Steel", type_2: "Dark"},
  #{name: "Bouffalant", pokedex_id: 626, type_1: "Normal", type_2: nil},
  #{name: "Rufflet", pokedex_id: 627, type_1: "Flying", type_2: "Normal"},
  #{name: "Braviary", pokedex_id: 628, type_1: "Flying", type_2: "Normal"},
  #{name: "Vullaby", pokedex_id: 629, type_1: "Flying", type_2: "Dark"},
  #{name: "Mandibuzz", pokedex_id: 630, type_1: "Flying", type_2: "Dark"},
  #{name: "Heatmor", pokedex_id: 631, type_1: "Fire", type_2: nil},
  #{name: "Durant", pokedex_id: 632, type_1: "Steel", type_2: "Bug"},
  #{name: "Deino", pokedex_id: 633, type_1: "Dragon", type_2: "Dark"},
  #{name: "Zweilous", pokedex_id: 634, type_1: "Dragon", type_2: "Dark"},
  #{name: "Hydreigon", pokedex_id: 635, type_1: "Dragon", type_2: "Dark"},
  #{name: "Larvesta", pokedex_id: 636, type_1: "Fire", type_2: "Bug"},
  #{name: "Volcarona", pokedex_id: 637, type_1: "Fire", type_2: "Bug"},
  #{name: "Cobalion", pokedex_id: 638, type_1: "Fighting", type_2: "Steel"},
  #{name: "Terrakion", pokedex_id: 639, type_1: "Fighting", type_2: "Rock"},
  #{name: "Virizion", pokedex_id: 640, type_1: "Fighting", type_2: "Grass"},
  #{name: "Tornadus Incarnate", pokedex_id: 641, type_1: "Flying", type_2: nil},
  #{name: "Thundurus Incarnate", pokedex_id: 642, type_1: "Flying", type_2: "Electric"},
  #{name: "Reshiram", pokedex_id: 643, type_1: "Fire", type_2: "Dragon"},
  #{name: "Zekrom", pokedex_id: 644, type_1: "Electric", type_2: "Dragon"},
  #{name: "Landorus Incarnate", pokedex_id: 645, type_1: "Flying", type_2: "Ground"},
  #{name: "Kyurem", pokedex_id: 646, type_1: "Ice", type_2: "Dragon"},
  #{name: "Keldeo Ordinary", pokedex_id: 647, type_1: "Fighting", type_2: "Water"},
  #{name: "Meloetta Aria", pokedex_id: 648, type_1: "Psychic", type_2: "Normal"},
  #{name: "Genesect", pokedex_id: 649, type_1: "Steel", type_2: "Bug"},
  #{name: "Chespin", pokedex_id: 650, type_1: "Grass", type_2: nil},
  #{name: "Quilladin", pokedex_id: 651, type_1: "Grass", type_2: nil},
  #{name: "Chesnaught", pokedex_id: 652, type_1: "Fighting", type_2: "Grass"},
  #{name: "Fennekin", pokedex_id: 653, type_1: "Fire", type_2: nil},
  #{name: "Braixen", pokedex_id: 654, type_1: "Fire", type_2: nil},
  #{name: "Delphox", pokedex_id: 655, type_1: "Psychic", type_2: "Fire"},
  #{name: "Froakie", pokedex_id: 656, type_1: "Water", type_2: nil},
  #{name: "Frogadier", pokedex_id: 657, type_1: "Water", type_2: nil},
  #{name: "Greninja", pokedex_id: 658, type_1: "Dark", type_2: "Water"},
  #{name: "Bunnelby", pokedex_id: 659, type_1: "Normal", type_2: nil},
  #{name: "Diggersby", pokedex_id: 660, type_1: "Ground", type_2: "Normal"},
  #{name: "Fletchling", pokedex_id: 661, type_1: "Flying", type_2: "Normal"},
  #{name: "Fletchinder", pokedex_id: 662, type_1: "Flying", type_2: "Fire"},
  #{name: "Talonflame", pokedex_id: 663, type_1: "Flying", type_2: "Fire"},
  #{name: "Scatterbug", pokedex_id: 664, type_1: "Bug", type_2: nil},
  #{name: "Spewpa", pokedex_id: 665, type_1: "Bug", type_2: nil},
  #{name: "Vivillon", pokedex_id: 666, type_1: "Flying", type_2: "Bug"},
  #{name: "Litleo", pokedex_id: 667, type_1: "Normal", type_2: "Fire"},
  #{name: "Pyroar", pokedex_id: 668, type_1: "Normal", type_2: "Fire"},
  #{name: "Flabebe", pokedex_id: 669, type_1: "Fairy", type_2: nil},
  #{name: "Floette", pokedex_id: 670, type_1: "Fairy", type_2: nil},
  #{name: "Florges", pokedex_id: 671, type_1: "Fairy", type_2: nil},
  #{name: "Skiddo", pokedex_id: 672, type_1: "Grass", type_2: nil},
  #{name: "Gogoat", pokedex_id: 673, type_1: "Grass", type_2: nil},
  #{name: "Pancham", pokedex_id: 674, type_1: "Fighting", type_2: nil},
  #{name: "Pangoro", pokedex_id: 675, type_1: "Dark", type_2: "Fighting"},
  #{name: "Furfrou", pokedex_id: 676, type_1: "Normal", type_2: nil},
  #{name: "Espurr", pokedex_id: 677, type_1: "Psychic", type_2: nil},
  #{name: "Meowstic Male", pokedex_id: 678, type_1: "Psychic", type_2: nil},
  #{name: "Honedge", pokedex_id: 679, type_1: "Ghost", type_2: "Steel"},
  #{name: "Doublade", pokedex_id: 680, type_1: "Ghost", type_2: "Steel"},
  #{name: "Aegislash Shield", pokedex_id: 681, type_1: "Ghost", type_2: "Steel"},
  #{name: "Spritzee", pokedex_id: 682, type_1: "Fairy", type_2: nil},
  #{name: "Aromatisse", pokedex_id: 683, type_1: "Fairy", type_2: nil},
  #{name: "Swirlix", pokedex_id: 684, type_1: "Fairy", type_2: nil},
  #{name: "Slurpuff", pokedex_id: 685, type_1: "Fairy", type_2: nil},
  #{name: "Inkay", pokedex_id: 686, type_1: "Psychic", type_2: "Dark"},
  #{name: "Malamar", pokedex_id: 687, type_1: "Psychic", type_2: "Dark"},
  #{name: "Binacle", pokedex_id: 688, type_1: "Water", type_2: "Rock"},
  #{name: "Barbaracle", pokedex_id: 689, type_1: "Water", type_2: "Rock"},
  #{name: "Skrelp", pokedex_id: 690, type_1: "Water", type_2: "Poison"},
  #{name: "Dragalge", pokedex_id: 691, type_1: "Dragon", type_2: "Poison"},
  #{name: "Clauncher", pokedex_id: 692, type_1: "Water", type_2: nil},
  #{name: "Clawitzer", pokedex_id: 693, type_1: "Water", type_2: nil},
  #{name: "Helioptile", pokedex_id: 694, type_1: "Normal", type_2: "Electric"},
  #{name: "Heliolisk", pokedex_id: 695, type_1: "Normal", type_2: "Electric"},
  #{name: "Tyrunt", pokedex_id: 696, type_1: "Dragon", type_2: "Rock"},
  #{name: "Tyrantrum", pokedex_id: 697, type_1: "Dragon", type_2: "Rock"},
  #{name: "Amaura", pokedex_id: 698, type_1: "Ice", type_2: "Rock"},
  #{name: "Aurorus", pokedex_id: 699, type_1: "Ice", type_2: "Rock"},
  #{name: "Sylveon", pokedex_id: 700, type_1: "Fairy", type_2: nil},
  #{name: "Hawlucha", pokedex_id: 701, type_1: "Flying", type_2: "Fighting"},
  #{name: "Dedenne", pokedex_id: 702, type_1: "Fairy", type_2: "Electric"},
  #{name: "Carbink", pokedex_id: 703, type_1: "Fairy", type_2: "Rock"},
  #{name: "Goomy", pokedex_id: 704, type_1: "Dragon", type_2: nil},
  #{name: "Sliggoo", pokedex_id: 705, type_1: "Dragon", type_2: nil},
  #{name: "Goodra", pokedex_id: 706, type_1: "Dragon", type_2: nil},
  #{name: "Klefki", pokedex_id: 707, type_1: "Fairy", type_2: "Steel"},
  #{name: "Phantump", pokedex_id: 708, type_1: "Grass", type_2: "Ghost"},
  #{name: "Trevenant", pokedex_id: 709, type_1: "Grass", type_2: "Ghost"},
  #{name: "Pumpkaboo Average", pokedex_id: 710, type_1: "Grass", type_2: "Ghost"},
  #{name: "Gourgeist Average", pokedex_id: 711, type_1: "Grass", type_2: "Ghost"},
  #{name: "Bergmite", pokedex_id: 712, type_1: "Ice", type_2: nil},
  #{name: "Avalugg", pokedex_id: 713, type_1: "Ice", type_2: nil},
  #{name: "Noibat", pokedex_id: 714, type_1: "Dragon", type_2: "Flying"},
  #{name: "Noivern", pokedex_id: 715, type_1: "Dragon", type_2: "Flying"},
  #{name: "Xerneas", pokedex_id: 716, type_1: "Fairy", type_2: nil},
  #{name: "Yveltal", pokedex_id: 717, type_1: "Flying", type_2: "Dark"},
  #{name: "Zygarde", pokedex_id: 718, type_1: "Ground", type_2: "Dragon"},
  #{name: "Diancie", pokedex_id: 719, type_1: "Fairy", type_2: "Rock"},
  #{name: "Hoopa", pokedex_id: 720, type_1: "Ghost", type_2: "Psychic"},
  #{name: "Volcanion", pokedex_id: 721, type_1: "Water", type_2: "Fire"},
  #{name: "Rowlet", pokedex_id: 722, type_1: "Flying", type_2: "Grass"},
  #{name: "Dartrix", pokedex_id: 723, type_1: "Flying", type_2: "Grass"},
  #{name: "Decidueye", pokedex_id: 724, type_1: "Ghost", type_2: "Grass"},
  #{name: "Litten", pokedex_id: 725, type_1: "Fire", type_2: nil},
  #{name: "Torracat", pokedex_id: 726, type_1: "Fire", type_2: nil},
  #{name: "Incineroar", pokedex_id: 727, type_1: "Dark", type_2: "Fire"},
  #{name: "Popplio", pokedex_id: 728, type_1: "Water", type_2: nil},
  #{name: "Brionne", pokedex_id: 729, type_1: "Water", type_2: nil},
  #{name: "Primarina", pokedex_id: 730, type_1: "Fairy", type_2: "Water"},
  #{name: "Pikipek", pokedex_id: 731, type_1: "Flying", type_2: "Normal"},
  #{name: "Trumbeak", pokedex_id: 732, type_1: "Flying", type_2: "Normal"},
  #{name: "Toucannon", pokedex_id: 733, type_1: "Flying", type_2: "Normal"},
  #{name: "Yungoos", pokedex_id: 734, type_1: "Normal", type_2: nil},
  #{name: "Gumshoos", pokedex_id: 735, type_1: "Normal", type_2: nil},
  #{name: "Grubbin", pokedex_id: 736, type_1: "Bug", type_2: nil},
  #{name: "Charjabug", pokedex_id: 737, type_1: "Electric", type_2: "Bug"},
  #{name: "Vikavolt", pokedex_id: 738, type_1: "Electric", type_2: "Bug"},
  #{name: "Crabrawler", pokedex_id: 739, type_1: "Fighting", type_2: nil},
  #{name: "Crabominable", pokedex_id: 740, type_1: "Ice", type_2: "Fighting"},
  #{name: "Oricorio Baile", pokedex_id: 741, type_1: "Flying", type_2: "Fire"},
  #{name: "Cutiefly", pokedex_id: 742, type_1: "Fairy", type_2: "Bug"},
  #{name: "Ribombee", pokedex_id: 743, type_1: "Fairy", type_2: "Bug"},
  #{name: "Rockruff", pokedex_id: 744, type_1: "Rock", type_2: nil},
  #{name: "Lycanroc Midday", pokedex_id: 745, type_1: "Rock", type_2: nil},
  #{name: "Wishiwashi Solo", pokedex_id: 746, type_1: "Water", type_2: nil},
  #{name: "Mareanie", pokedex_id: 747, type_1: "Water", type_2: "Poison"},
  #{name: "Toxapex", pokedex_id: 748, type_1: "Water", type_2: "Poison"},
  #{name: "Mudbray", pokedex_id: 749, type_1: "Ground", type_2: nil},
  #{name: "Mudsdale", pokedex_id: 750, type_1: "Ground", type_2: nil},
  #{name: "Dewpider", pokedex_id: 751, type_1: "Bug", type_2: "Water"},
  #{name: "Araquanid", pokedex_id: 752, type_1: "Bug", type_2: "Water"},
  #{name: "Fomantis", pokedex_id: 753, type_1: "Grass", type_2: nil},
  #{name: "Lurantis", pokedex_id: 754, type_1: "Grass", type_2: nil},
  #{name: "Morelull", pokedex_id: 755, type_1: "Fairy", type_2: "Grass"},
  #{name: "Shiinotic", pokedex_id: 756, type_1: "Fairy", type_2: "Grass"},
  #{name: "Salandit", pokedex_id: 757, type_1: "Fire", type_2: "Poison"},
  #{name: "Salazzle", pokedex_id: 758, type_1: "Fire", type_2: "Poison"},
  #{name: "Stufful", pokedex_id: 759, type_1: "Fighting", type_2: "Normal"},
  #{name: "Bewear", pokedex_id: 760, type_1: "Fighting", type_2: "Normal"},
  #{name: "Bounsweet", pokedex_id: 761, type_1: "Grass", type_2: nil},
  #{name: "Steenee", pokedex_id: 762, type_1: "Grass", type_2: nil},
  #{name: "Tsareena", pokedex_id: 763, type_1: "Grass", type_2: nil},
  #{name: "Comfey", pokedex_id: 764, type_1: "Fairy", type_2: nil},
  #{name: "Oranguru", pokedex_id: 765, type_1: "Psychic", type_2: "Normal"},
  #{name: "Passimian", pokedex_id: 766, type_1: "Fighting", type_2: nil},
  #{name: "Wimpod", pokedex_id: 767, type_1: "Water", type_2: "Bug"},
  #{name: "Golisopod", pokedex_id: 768, type_1: "Water", type_2: "Bug"},
  #{name: "Sandygast", pokedex_id: 769, type_1: "Ground", type_2: "Ghost"},
  #{name: "Palossand", pokedex_id: 770, type_1: "Ground", type_2: "Ghost"},
  #{name: "Pyukumuku", pokedex_id: 771, type_1: "Water", type_2: nil},
  #{name: "Type Null", pokedex_id: 772, type_1: "Normal", type_2: nil},
  #{name: "Silvally", pokedex_id: 773, type_1: "Normal", type_2: nil},
  #{name: "Minior Red Meteor", pokedex_id: 774, type_1: "Flying", type_2: "Rock"},
  #{name: "Komala", pokedex_id: 775, type_1: "Normal", type_2: nil},
  #{name: "Turtonator", pokedex_id: 776, type_1: "Dragon", type_2: "Fire"},
  #{name: "Togedemaru", pokedex_id: 777, type_1: "Steel", type_2: "Electric"},
  #{name: "Mimikyu Disguised", pokedex_id: 778, type_1: "Fairy", type_2: "Ghost"},
  #{name: "Bruxish", pokedex_id: 779, type_1: "Psychic", type_2: "Water"},
  #{name: "Drampa", pokedex_id: 780, type_1: "Dragon", type_2: "Normal"},
  #{name: "Dhelmise", pokedex_id: 781, type_1: "Grass", type_2: "Ghost"},
  #{name: "Jangmo O", pokedex_id: 782, type_1: "Dragon", type_2: nil},
  #{name: "Hakamo O", pokedex_id: 783, type_1: "Fighting", type_2: "Dragon"},
  #{name: "Kommo O", pokedex_id: 784, type_1: "Fighting", type_2: "Dragon"},
  #{name: "Tapu Koko", pokedex_id: 785, type_1: "Fairy", type_2: "Electric"},
  #{name: "Tapu Lele", pokedex_id: 786, type_1: "Fairy", type_2: "Psychic"},
  #{name: "Tapu Bulu", pokedex_id: 787, type_1: "Fairy", type_2: "Grass"},
  #{name: "Tapu Fini", pokedex_id: 788, type_1: "Fairy", type_2: "Water"},
  #{name: "Cosmog", pokedex_id: 789, type_1: "Psychic", type_2: nil},
  #{name: "Cosmoem", pokedex_id: 790, type_1: "Psychic", type_2: nil},
  #{name: "Solgaleo", pokedex_id: 791, type_1: "Steel", type_2: "Psychic"},
  #{name: "Lunala", pokedex_id: 792, type_1: "Ghost", type_2: "Psychic"},
  #{name: "Nihilego", pokedex_id: 793, type_1: "Poison", type_2: "Rock"},
  #{name: "Buzzwole", pokedex_id: 794, type_1: "Fighting", type_2: "Bug"},
  #{name: "Pheromosa", pokedex_id: 795, type_1: "Fighting", type_2: "Bug"},
  #{name: "Xurkitree", pokedex_id: 796, type_1: "Electric", type_2: nil},
  #{name: "Celesteela", pokedex_id: 797, type_1: "Flying", type_2: "Steel"},
  #{name: "Kartana", pokedex_id: 798, type_1: "Steel", type_2: "Grass"},
  #{name: "Guzzlord", pokedex_id: 799, type_1: "Dragon", type_2: "Dark"},
  #{name: "Necrozma", pokedex_id: 800, type_1: "Psychic", type_2: nil},
  #{name: "Magearna", pokedex_id: 801, type_1: "Fairy", type_2: "Steel"},
  #{name: "Marshadow", pokedex_id: 802, type_1: "Ghost", type_2: "Fighting"}
   ])

eric = Trainer.create(username:"eric", password:"123", money: 10000)

  # -1 Thunder Stone
  # -2 Moon Stone
  # -3 Fire Stone
  # -4 Leaf Stone
  # -5 Water Stone
  # -6 Trade

Family.create([
  {pokemon_id: 1, evolution_id: 2, level: 18},
  {pokemon_id: 2, evolution_id: 3, level: 32},
  {pokemon_id: 4, evolution_id: 5, level: 16},
  {pokemon_id: 5, evolution_id: 6, level: 36},
  {pokemon_id: 7, evolution_id: 8, level: 18},
  {pokemon_id: 8, evolution_id: 9, level: 36},
  {pokemon_id: 10, evolution_id: 11, level: 7},
  {pokemon_id: 11, evolution_id: 12, level: 10},
  {pokemon_id: 13, evolution_id: 14, level: 7},
  {pokemon_id: 14, evolution_id: 15, level: 10},
  {pokemon_id: 16, evolution_id: 17, level: 18},
  {pokemon_id: 17, evolution_id: 18, level: 36},
  {pokemon_id: 19, evolution_id: 20, level: 20},
  {pokemon_id: 21, evolution_id: 22, level: 20},
  {pokemon_id: 23, evolution_id: 24, level: 22},
  {pokemon_id: 25, evolution_id: 26, level: -1},
  {pokemon_id: 27, evolution_id: 28, level: 22},
  {pokemon_id: 29, evolution_id: 30, level: 16},
  {pokemon_id: 30, evolution_id: 31, level: -2},
  {pokemon_id: 32, evolution_id: 33, level: 16},
  {pokemon_id: 33, evolution_id: 34, level: -2},
  {pokemon_id: 35, evolution_id: 36, level: -2},
  {pokemon_id: 37, evolution_id: 38, level: -3},
  {pokemon_id: 39, evolution_id: 40, level: -2},
  {pokemon_id: 41, evolution_id: 42, level: 22},
  {pokemon_id: 43, evolution_id: 44, level: 21},
  {pokemon_id: 44, evolution_id: 45, level: -4},
  {pokemon_id: 46, evolution_id: 47, level: 24},
  {pokemon_id: 48, evolution_id: 49, level: 31},
  {pokemon_id: 50, evolution_id: 51, level: 26},
  {pokemon_id: 52, evolution_id: 53, level: 28},
  {pokemon_id: 54, evolution_id: 55, level: 33},
  {pokemon_id: 56, evolution_id: 57, level: 28},
  {pokemon_id: 58, evolution_id: 59, level: -3},
  {pokemon_id: 60, evolution_id: 61, level: 25},
  {pokemon_id: 61, evolution_id: 62, level: -5},
  {pokemon_id: 63, evolution_id: 64, level: 16},
  {pokemon_id: 64, evolution_id: 65, level: -6},
  {pokemon_id: 66, evolution_id: 67, level: 28},
  {pokemon_id: 67, evolution_id: 68, level: -6},
  {pokemon_id: 69, evolution_id: 70, level: 21},
  {pokemon_id: 70, evolution_id: 71, level: -4},
  {pokemon_id: 74, evolution_id: 75, level: 25},
  {pokemon_id: 75, evolution_id: 76, level: -6},
  {pokemon_id: 77, evolution_id: 78, level: 40},
  {pokemon_id: 79, evolution_id: 80, level: 37},
  {pokemon_id: 81, evolution_id: 82, level: 30},
  {pokemon_id: 84, evolution_id: 85, level: 31},
  {pokemon_id: 86, evolution_id: 87, level: 34},
  {pokemon_id: 88, evolution_id: 89, level: 38},
  {pokemon_id: 90, evolution_id: 91, level: -5},
  {pokemon_id: 92, evolution_id: 93, level: 25},
  {pokemon_id: 93, evolution_id: 94, level: -6},
  {pokemon_id: 96, evolution_id: 97, level: 26},
  {pokemon_id: 98, evolution_id: 99, level: 28},
  {pokemon_id: 100, evolution_id: 101, level: 30},
  {pokemon_id: 102, evolution_id: 103, level: -4},
  {pokemon_id: 104, evolution_id: 105, level: 28},
  {pokemon_id: 109, evolution_id: 110, level: 35},
  {pokemon_id: 111, evolution_id: 112, level: 42},
  {pokemon_id: 116, evolution_id: 117, level: 32},
  {pokemon_id: 118, evolution_id: 119, level: 33},
  {pokemon_id: 120, evolution_id: 121, level: -5},
  {pokemon_id: 129, evolution_id: 130, level: 20},
  {pokemon_id: 133, evolution_id: 134, level: -5},
  {pokemon_id: 133, evolution_id: 135, level: -1},
  {pokemon_id: 133, evolution_id: 136, level: -3},
  {pokemon_id: 138, evolution_id: 139, level: 40},
  {pokemon_id: 140, evolution_id: 141, level: 40},
  {pokemon_id: 147, evolution_id: 148, level: 30},
  {pokemon_id: 148, evolution_id: 149, level: 55}
])

Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
Pokeball.create(trainer: eric, pokemon_id: rand(1..151), level: rand(1..100))
